### ISSUE TITLE
Add house denied

### ISSUE THREAD

**Issue by 1920x1080xD** [TJ-Droid/tjdroid#18]
If we hold an house, we have a popup menu with the choice: Denied, Delete. When we clicked on denied, the house is crossed out and glows red.

(I don’t know very well what word is used in English, if a person refused to talk to us, perhaps instead of denied there will be another word)

![NG20231203-103955](https://github.com/TJ-Droid/tjdroid/assets/97390504/2efe1a0e-cf52-4994-8ec5-313ad9efaa3a)

**Comment by pedropaulodf** [comment]
Hello, 1920x1080xD!

I think I understand your demand. You would like to add one more option in addition to the 5 that already exist, right?
I would like us to add an option of: **Refused** or **Denied**. 
If so, in Russian, what would the word be?
